# Generated by Django 5.2.4 on 2025-08-03 17:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("museum", models.CharField(blank=True, max_length=255)),
                ("material", models.CharField(blank=True, max_length=255)),
                ("source", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="images", to="visor.tag"
                    ),
                ),
            ],
        ),
    ]
